services:
  jekyll:
    image: jekyll/jekyll:latest
    command: jekyll serve --watch --host 0.0.0.0 --verbose --incremental --livereload
    ports:
      - "4000:4000"
      - "35729:35729"  # LiveReload port
    volumes:
      - .:/srv/jekyll
      - bundle_cache:/usr/local/bundle
    environment:
      - JEKYLL_ENV=development
    stdin_open: true
    tty: true

volumes:
  bundle_cache: